CREATE DATABASE DShieldpy;
USE DShieldpy;
CREATE TABLE attack (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, tstamp DATETIME NOT NULL, src INT UNSIGNED NOT NULL, spt SMALLINT UNSIGNED NULL, dst INT UNSIGNED NOT NULL, dpt SMALLINT UNSIGNED NULL, proto TINYINT UNSIGNED NOT NULL, flags TINYINT UNSIGNED NULL, count INT UNSIGNED NOT NULL DEFAULT 1, method TINYINT UNSIGNED NOT NULL, INDEX idxmethod (method), INDEX idxsource (src), INDEX idxdstdpt (dst, dpt), INDEX idxdpt (dpt));
CREATE TABLE method (id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, name VARCHAR(10) NOT NULL, url VARCHAR(50) NULL);
INSERT INTO method VALUES (NULL, "ipchains", NULL);
INSERT INTO method VALUES (NULL, "iptables", "http://www.netfilter.org/");
INSERT INTO method VALUES (NULL, "snort", "http://www.snort.org/");
